### ISSUE TITLE
Cannot chose color "No GUI Implemented" since 2.0.0

### ISSUE THREAD

**Issue by Orthopoxvirus** [IvanMurzak/Unity-Theme#11]
Hey, I just updated to 2.0.0. Love all the new stuff, but I get this message in the color binders:
![image](https://github.com/IvanMurzak/Unity-Theme/assets/22443072/030f9fca-7fc5-4b63-be65-9493e901001a)

Version: 2.0.0
Unity Version: 2022.3.6f1

Any idea how to fix that?

Cheers, Michael

**Comment by IvanMurzak** [comment]
Thank you @Orthopoxvirus for the report. I am working on it.

**Comment by IvanMurzak** [comment]
For some reason, Unity UI Elements has an issue with rendering these components in case it is integrated as a package. It is fixed by adding an old GUI interface support. It is not as cool as it should be with UI elements. Anyway, version 2.0.1 supports two render options, with a bigger priority on UI elements. 

![image](https://github.com/IvanMurzak/Unity-Theme/assets/9135028/ae3b89a6-60b2-414d-84f5-5683e6d08797)

As only Unity will fix it, it will be rendered with a color preview circle like here:
![image](https://github.com/IvanMurzak/Unity-Theme/assets/9135028/f8846334-e6c6-41a5-89d5-9ce697573c26)

**Comment by Orthopoxvirus** [comment]
Hey, sorry for the late message. That was a really fast fix. I just updated and can confirm, that everything works great.

Cheers,
Michael
