### ISSUE TITLE
Changing theme at runtime

### ISSUE THREAD

**Issue by codyrchildress** [IvanMurzak/Unity-Theme#4]
Hi there,

Thank you for sharing this wonderful asset. Is it possible to change the theme at runtime? I am hoping to use this to implement a day/night mode on my game. 

Cheers,
Cody

**Comment by IvanMurzak** [comment]
@codyrchildress hi. Thank you! Yes, it works in Edit Time and in Play Time (runtime).

**Comment by codyrchildress** [comment]
> @codyrchildress hi. Thank you! Yes, it works in Edit Time and in Play Time (runtime).

Sorry, but how exactly can this be done?

**Comment by IvanMurzak** [comment]
@codyrchildress You can do that using C# API of the package.

```C#
// Link ThemeDatabase, 
// path to the file in your project: `/Assets/Resources/Unity-Theme Database.asset`
[SerializedField] ThemeDatabase themeDatabase;

// change current time to a new theme in themes list
themeDatabase.CurrentThemeIndex = 1;
```

**Comment by iiidefektiii** [comment]
Is it possible to get the list of themes from another script and set it instead of by name or index? 
Example. I create a ThemeManager script to call it by name but would be awesome if I could get the list of available themes and set it within in my script. this way each scene can have its own theme set.
